services:
  - type: web
    name: clock-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn clock_server:app"
    autoDeploy: true